[2025-08-22T15:36:01.497+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-22T15:36:01.555+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_stock_data.fetch_and_store_stock_data scheduled__2025-08-21T00:00:00+00:00 [queued]>
[2025-08-22T15:36:01.571+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_stock_data.fetch_and_store_stock_data scheduled__2025-08-21T00:00:00+00:00 [queued]>
[2025-08-22T15:36:01.572+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2025-08-22T15:36:01.598+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): fetch_and_store_stock_data> on 2025-08-21 00:00:00+00:00
[2025-08-22T15:36:01.608+0000] {standard_task_runner.py:63} INFO - Started process 58 to run task
[2025-08-22T15:36:01.616+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_stock_data', 'fetch_and_store_stock_data', 'scheduled__2025-08-21T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/fetch_stock_data.py', '--cfg-path', '/tmp/tmph5q8tc7m']
[2025-08-22T15:36:01.621+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask fetch_and_store_stock_data
[2025-08-22T15:36:01.731+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_stock_data.fetch_and_store_stock_data scheduled__2025-08-21T00:00:00+00:00 [running]> on host e557fe80712b
[2025-08-22T15:36:02.038+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_stock_data' AIRFLOW_CTX_TASK_ID='fetch_and_store_stock_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-21T00:00:00+00:00'
[2025-08-22T15:36:02.042+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-22T15:36:05.497+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-22T15:36:05.505+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fetch_stock_data.py", line 36, in fetch_and_store
    cur.execute("""
psycopg2.errors.UndefinedTable: relation "daily_prices" does not exist
LINE 2:                 INSERT INTO daily_prices (symbol, date, open...
                                    ^

[2025-08-22T15:36:05.605+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=fetch_stock_data, task_id=fetch_and_store_stock_data, execution_date=20250821T000000, start_date=20250822T153601, end_date=20250822T153605
[2025-08-22T15:36:05.653+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task fetch_and_store_stock_data (relation "daily_prices" does not exist
LINE 2:                 INSERT INTO daily_prices (symbol, date, open...
                                    ^
; 58)
[2025-08-22T15:36:05.827+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-22T15:36:05.944+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-22T15:36:05.951+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
